#!/bin/bash

#Usage: ./hxNewVM <userName> <VM_Number> <dist>
#Ex: ./hxNewVM testUser 1 squeeze

hxHostname="$1-$2"."$(hostname -f)"

xen-create-image --hostname "$hxHostname" --ip auto --gateway 10.0.0.1 --netmask 255.255.255.0 --vcpus 2 --pygrub --fs=ext4 --dist "$3"

echo "$hxHostname" >> /home/"$1"/xenList

#http://xen.1045712.n5.nabble.com/console-access-to-non-root-xen-3-0-td2560667.html
mkdir -p /etc/sudoers.d
echo "$1 ALL=NOPASSWD:/usr/sbin/xm console $hxHostname, /usr/sbin/xm create -c /etc/xen/$hxHostname.cfg, /usr/sbin/xm create /etc/xen/$hxHostname.cfg, /usr/sbin/xm destroy $hxHostname, /usr/sbin/reimage-dom $hxHostname ?" > /etc/sudoers.d/xen-"$hxHostname"

/etc/init.d/sudo restart